<a href="https://colab.research.google.com/github/Pigpod/LATIA112-2/blob/main/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [44]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [45]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[-0.7630,  0.0257, -0.6550,  1.4232, -0.7344],
        [-1.0203, -1.0074,  0.3584, -1.4293, -1.2982],
        [ 1.6793, -1.4287, -0.4630,  0.9128,  0.8197],
        [-1.9786,  2.0928, -0.2289,  0.0312,  0.7536]])
tensor([[-1.0595, -1.6522, -1.3525,  0.5975, -0.4937],
        [ 0.2208,  1.1735, -0.0144,  0.3973,  0.1206],
        [-1.1922, -0.4492, -0.0368, -0.3389,  0.6576],
        [ 0.6047,  0.2418, -0.8399, -0.5888, -0.1577]])
tensor([[ 0.7886, -1.2592, -0.4436,  1.9525, -0.4869],
        [-0.6450, -0.1776, -0.9026,  1.5416, -0.7037],
        [ 2.2935,  0.4732,  0.4649, -0.8547, -0.3185],
        [ 0.5333,  0.4185, -0.6481, -0.3292,  0.6392]])


In [46]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(2.0928)


In [47]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([1.6793, 2.0928, 0.3584, 1.4232, 0.8197])
tensor([2, 3, 1, 0, 2])


In [48]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([1.6793, 2.0928, 0.3584, 1.4232, 0.8197])
tensor([2, 3, 1, 0, 2])


In [49]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([1.6793, 2.0928, 0.3584, 1.4232, 0.8197])
tensor([2, 3, 1, 0, 2])


In [50]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[1.6793, 2.0928, 0.3584, 1.4232, 0.8197]])
tensor([[2, 3, 1, 0, 2]])


In [51]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])


tensor([1.6793, 2.0928, 0.3584, 1.4232, 0.8197])
tensor([2, 3, 1, 0, 2])


/tmp/ipykernel_874/1447715753.py:3: UserWarning: An output with one or more elements was resized since it had shape [1, 5], which does not match the required output shape [5]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /pytorch/aten/src/ATen/native/Resize.cpp:31.)
  torch.max(x,0,False,out=p)


In [52]:
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])

tensor([1.6793, 2.0928, 0.3584, 1.4232, 0.8197])
tensor([2, 3, 1, 0, 2])


In [53]:
# 2-7
m, idx = torch.max(x,0,True)

In [54]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[-0.7630,  0.0257, -0.6550,  1.4232, -0.4937],
        [ 0.2208,  1.1735,  0.3584,  0.3973,  0.1206],
        [ 1.6793, -0.4492, -0.0368,  0.9128,  0.8197],
        [ 0.6047,  2.0928, -0.2289,  0.0312,  0.7536]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [83]:
import torch

In [88]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)

In [89]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [79]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(4,5)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [82]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [ ]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [ ]:
for datapoint in dataset:
  print(datapoint)

When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array.



torch.utils.data.DataLoader will need two imformation to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the imformation by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [ ]:
import torch
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [ ]:
import torch.utils.data
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"

  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]

  def __len__(self): # What is the length of the dataset
    return 2 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)